package com.sigeye.core.ble

// GENERATED FILE - do not edit by hand.
// Source: Bluetooth SIG assigned numbers (appearance_values.yaml, member_uuids.yaml) and
// the Nordic bluetooth-numbers-database (service_uuids.json).
// Regenerate with scratchpad/gen_ble_tables.py then scratchpad/emit_tables.py.

/**
 * The Bluetooth SIG's registries, as lookup tables.
 *
 * Transcribed by a script rather than by hand: an earlier hand-typed vendor table had five
 * wrong entries out of twenty-three, and a confidently wrong label is worse than none.
 */
object AssignedNumbers {

    /** GAP Appearance categories - the top ten bits of the appearance value. */
    val APPEARANCE_CATEGORIES: Map<Int, String> = mapOf(
        0x000 to "Unknown",
        0x001 to "Phone",
        0x002 to "Computer",
        0x003 to "Watch",
        0x004 to "Clock",
        0x005 to "Display",
        0x006 to "Remote Control",
        0x007 to "Eye-glasses",
        0x008 to "Tag",
        0x009 to "Keyring",
        0x00A to "Media Player",
        0x00B to "Barcode Scanner",
        0x00C to "Thermometer",
        0x00D to "Heart Rate Sensor",
        0x00E to "Blood Pressure",
        0x00F to "Human Interface Device",
        0x010 to "Glucose Meter",
        0x011 to "Running Walking Sensor",
        0x012 to "Cycling",
        0x013 to "Control Device",
        0x014 to "Network Device",
        0x015 to "Sensor",
        0x016 to "Light Fixtures",
        0x017 to "Fan",
        0x018 to "HVAC",
        0x019 to "Air Conditioning",
        0x01A to "Humidifier",
        0x01B to "Heating",
        0x01C to "Access Control",
        0x01D to "Motorized Device",
        0x01E to "Power Device",
        0x01F to "Light Source",
        0x020 to "Window Covering",
        0x021 to "Audio Sink",
        0x022 to "Audio Source",
        0x023 to "Motorized Vehicle",
        0x024 to "Domestic Appliance",
        0x025 to "Wearable Audio Device",
        0x026 to "Aircraft",
        0x027 to "AV Equipment",
        0x028 to "Display Equipment",
        0x029 to "Hearing aid",
        0x02A to "Gaming",
        0x02B to "Signage",
        0x031 to "Pulse Oximeter",
        0x032 to "Weight Scale",
        0x033 to "Personal Mobility Device",
        0x034 to "Continuous Glucose Monitor",
        0x035 to "Insulin Pump",
        0x036 to "Medication Delivery",
        0x037 to "Spirometer",
        0x051 to "Outdoor Sports Activity",
        0x052 to "Industrial Measurement Device",
        0x053 to "Industrial Tools",
        0x054 to "Cookware Device",
    )

    /** Subcategories, keyed by category then by the low six bits. */
    val APPEARANCE_SUBCATEGORIES: Map<Int, Map<Int, String>> = mapOf(
        0x002 to mapOf(1 to "Desktop Workstation", 2 to "Server-class Computer", 3 to "Laptop", 4 to "Handheld PC/PDA (clamshell)", 5 to "Palm-size PC/PDA", 6 to "Wearable computer (watch size)", 7 to "Tablet", 8 to "Docking Station", 9 to "All in One", 10 to "Blade Server", 11 to "Convertible", 12 to "Detachable", 13 to "IoT Gateway", 14 to "Mini PC", 15 to "Stick PC"),
        0x003 to mapOf(1 to "Sports Watch", 2 to "Smartwatch"),
        0x00C to mapOf(1 to "Ear Thermometer"),
        0x00D to mapOf(1 to "Heart Rate Belt"),
        0x00E to mapOf(1 to "Arm Blood Pressure", 2 to "Wrist Blood Pressure"),
        0x00F to mapOf(1 to "Keyboard", 2 to "Mouse", 3 to "Joystick", 4 to "Gamepad", 5 to "Digitizer Tablet", 6 to "Card Reader", 7 to "Digital Pen", 8 to "Barcode Scanner", 9 to "Touchpad", 10 to "Presentation Remote"),
        0x011 to mapOf(1 to "In-Shoe Running Walking Sensor", 2 to "On-Shoe Running Walking Sensor", 3 to "On-Hip Running Walking Sensor"),
        0x012 to mapOf(1 to "Cycling Computer", 2 to "Speed Sensor", 3 to "Cadence Sensor", 4 to "Power Sensor", 5 to "Speed and Cadence Sensor"),
        0x013 to mapOf(1 to "Switch", 2 to "Multi-switch", 3 to "Button", 4 to "Slider", 5 to "Rotary Switch", 6 to "Touch Panel", 7 to "Single Switch", 8 to "Double Switch", 9 to "Triple Switch", 10 to "Battery Switch", 11 to "Energy Harvesting Switch", 12 to "Push Button", 13 to "Dial"),
        0x014 to mapOf(1 to "Access Point", 2 to "Mesh Device", 3 to "Mesh Network Proxy"),
        0x015 to mapOf(1 to "Motion Sensor", 2 to "Air quality Sensor", 3 to "Temperature Sensor", 4 to "Humidity Sensor", 5 to "Leak Sensor", 6 to "Smoke Sensor", 7 to "Occupancy Sensor", 8 to "Contact Sensor", 9 to "Carbon Monoxide Sensor", 10 to "Carbon Dioxide Sensor", 11 to "Ambient Light Sensor", 12 to "Energy Sensor", 13 to "Color Light Sensor", 14 to "Rain Sensor", 15 to "Fire Sensor", 16 to "Wind Sensor", 17 to "Proximity Sensor", 18 to "Multi-Sensor", 19 to "Flush Mounted Sensor", 20 to "Ceiling Mounted Sensor", 21 to "Wall Mounted Sensor", 22 to "Multisensor", 23 to "Energy Meter", 24 to "Flame Detector", 25 to "Vehicle Tire Pressure Sensor"),
        0x016 to mapOf(1 to "Wall Light", 2 to "Ceiling Light", 3 to "Floor Light", 4 to "Cabinet Light", 5 to "Desk Light", 6 to "Troffer Light", 7 to "Pendant Light", 8 to "In-ground Light", 9 to "Flood Light", 10 to "Underwater Light", 11 to "Bollard with Light", 12 to "Pathway Light", 13 to "Garden Light", 14 to "Pole-top Light", 15 to "Spotlight", 16 to "Linear Light", 17 to "Street Light", 18 to "Shelves Light", 19 to "Bay Light", 20 to "Emergency Exit Light", 21 to "Light Controller", 22 to "Light Driver", 23 to "Bulb", 24 to "Low-bay Light", 25 to "High-bay Light"),
        0x017 to mapOf(1 to "Ceiling Fan", 2 to "Axial Fan", 3 to "Exhaust Fan", 4 to "Pedestal Fan", 5 to "Desk Fan", 6 to "Wall Fan"),
        0x018 to mapOf(1 to "Thermostat", 2 to "Humidifier", 3 to "De-humidifier", 4 to "Heater", 5 to "Radiator", 6 to "Boiler", 7 to "Heat Pump", 8 to "Infrared Heater", 9 to "Radiant Panel Heater", 10 to "Fan Heater", 11 to "Air Curtain"),
        0x01B to mapOf(1 to "Radiator", 2 to "Boiler", 3 to "Heat Pump", 4 to "Infrared Heater", 5 to "Radiant Panel Heater", 6 to "Fan Heater", 7 to "Air Curtain"),
        0x01C to mapOf(1 to "Access Door", 2 to "Garage Door", 3 to "Emergency Exit Door", 4 to "Access Lock", 5 to "Elevator", 6 to "Window", 7 to "Entrance Gate", 8 to "Door Lock", 9 to "Locker"),
        0x01D to mapOf(1 to "Motorized Gate", 2 to "Awning", 3 to "Blinds or Shades", 4 to "Curtains", 5 to "Screen"),
        0x01E to mapOf(1 to "Power Outlet", 2 to "Power Strip", 3 to "Plug", 4 to "Power Supply", 5 to "LED Driver", 6 to "Fluorescent Lamp Gear", 7 to "HID Lamp Gear", 8 to "Charge Case", 9 to "Power Bank"),
        0x01F to mapOf(1 to "Incandescent Light Bulb", 2 to "LED Lamp", 3 to "HID Lamp", 4 to "Fluorescent Lamp", 5 to "LED Array", 6 to "Multi-Color LED Array", 7 to "Low voltage halogen", 8 to "Organic light emitting diode (OLED)"),
        0x020 to mapOf(1 to "Window Shades", 2 to "Window Blinds", 3 to "Window Awning", 4 to "Window Curtain", 5 to "Exterior Shutter", 6 to "Exterior Screen"),
        0x021 to mapOf(1 to "Standalone Speaker", 2 to "Soundbar", 3 to "Bookshelf Speaker", 4 to "Standmounted Speaker", 5 to "Speakerphone"),
        0x022 to mapOf(1 to "Microphone", 2 to "Alarm", 3 to "Bell", 4 to "Horn", 5 to "Broadcasting Device", 6 to "Service Desk", 7 to "Kiosk", 8 to "Broadcasting Room", 9 to "Auditorium"),
        0x023 to mapOf(1 to "Car", 2 to "Large Goods Vehicle", 3 to "2-Wheeled Vehicle", 4 to "Motorbike", 5 to "Scooter", 6 to "Moped", 7 to "3-Wheeled Vehicle", 8 to "Light Vehicle", 9 to "Quad Bike", 10 to "Minibus", 11 to "Bus", 12 to "Trolley", 13 to "Agricultural Vehicle", 14 to "Camper / Caravan", 15 to "Recreational Vehicle / Motor Home"),
        0x024 to mapOf(1 to "Refrigerator", 2 to "Freezer", 3 to "Oven", 4 to "Microwave", 5 to "Toaster", 6 to "Washing Machine", 7 to "Dryer", 8 to "Coffee maker", 9 to "Clothes iron", 10 to "Curling iron", 11 to "Hair dryer", 12 to "Vacuum cleaner", 13 to "Robotic vacuum cleaner", 14 to "Rice cooker", 15 to "Clothes steamer"),
        0x025 to mapOf(1 to "Earbud", 2 to "Headset", 3 to "Headphones", 4 to "Neck Band", 5 to "Left Earbud", 6 to "Right Earbud"),
        0x026 to mapOf(1 to "Light Aircraft", 2 to "Microlight", 3 to "Paraglider", 4 to "Large Passenger Aircraft"),
        0x027 to mapOf(1 to "Amplifier", 2 to "Receiver", 3 to "Radio", 4 to "Tuner", 5 to "Turntable", 6 to "CD Player", 7 to "DVD Player", 8 to "Bluray Player", 9 to "Optical Disc Player", 10 to "Set-Top Box"),
        0x028 to mapOf(1 to "Television", 2 to "Monitor", 3 to "Projector"),
        0x029 to mapOf(1 to "In-ear hearing aid", 2 to "Behind-ear hearing aid", 3 to "Cochlear Implant"),
        0x02A to mapOf(1 to "Home Video Game Console", 2 to "Portable handheld console"),
        0x02B to mapOf(1 to "Digital Signage", 2 to "Electronic Label"),
        0x031 to mapOf(1 to "Fingertip Pulse Oximeter", 2 to "Wrist Worn Pulse Oximeter"),
        0x033 to mapOf(1 to "Powered Wheelchair", 2 to "Mobility Scooter"),
        0x035 to mapOf(1 to "Insulin Pump, durable pump", 4 to "Insulin Pump, patch pump", 8 to "Insulin Pen"),
        0x037 to mapOf(1 to "Handheld Spirometer"),
        0x051 to mapOf(1 to "Location Display", 2 to "Location and Navigation Display", 3 to "Location Pod", 4 to "Location and Navigation Pod"),
        0x052 to mapOf(1 to "Torque Testing Device", 2 to "Caliper", 3 to "Dial Indicator", 4 to "Micrometer", 5 to "Height Gauge", 6 to "Force Gauge"),
        0x053 to mapOf(1 to "Machine Tool Holder", 2 to "Generic Clamping Device", 3 to "Clamping Jaws/Jaw Chuck", 4 to "Clamping (Collet) Chuck", 5 to "Clamping Mandrel", 6 to "Vise", 7 to "Zero-Point Clamping System", 8 to "Torque Wrench", 9 to "Torque Screwdriver"),
        0x054 to mapOf(1 to "Pot and Jugs", 2 to "Pressure Cooker", 3 to "Slow Cooker", 4 to "Steam Cooker", 5 to "Saucepan", 6 to "Frying Pan", 7 to "Casserole", 8 to "Dutch Oven", 9 to "Grill Pan/Raclette Grill/Griddle Pan", 10 to "Braising Pan", 11 to "Wok Pan", 12 to "Paella Pan", 13 to "Crepe Pan", 14 to "Tagine", 15 to "Fondue", 16 to "Lid", 17 to "Wired Probe", 18 to "Wireless Probe", 19 to "Baking Molds", 20 to "Baking Tray"),
    )

    /** 16-bit services defined by the SIG: what the device can do. */
    val SIG_SERVICES: Map<Int, String> = mapOf(
        0x1800 to "Generic Access",
        0x1801 to "Generic Attribute",
        0x1802 to "Immediate Alert",
        0x1803 to "Link Loss",
        0x1804 to "Tx Power",
        0x1805 to "Current Time Service",
        0x1806 to "Reference Time Update Service",
        0x1807 to "Next DST Change Service",
        0x1808 to "Glucose",
        0x1809 to "Health Thermometer",
        0x180A to "Device Information",
        0x180D to "Heart Rate",
        0x180E to "Phone Alert Status Service",
        0x180F to "Battery Service",
        0x1810 to "Blood Pressure",
        0x1811 to "Alert Notification Service",
        0x1812 to "Human Interface Device",
        0x1813 to "Scan Parameters",
        0x1814 to "Running Speed and Cadence",
        0x1815 to "Automation IO",
        0x1816 to "Cycling Speed and Cadence",
        0x1818 to "Cycling Power",
        0x1819 to "Location and Navigation",
        0x181A to "Environmental Sensing",
        0x181B to "Body Composition",
        0x181C to "User Data",
        0x181D to "Weight Scale",
        0x181E to "Bond Management Service",
        0x181F to "Continuous Glucose Monitoring",
        0x1820 to "Internet Protocol Support Service",
        0x1821 to "Indoor Positioning",
        0x1822 to "Pulse Oximeter Service",
        0x1823 to "HTTP Proxy",
        0x1824 to "Transport Discovery",
        0x1825 to "Object Transfer Service",
        0x1826 to "Fitness Machine",
        0x1827 to "Mesh Provisioning Service",
        0x1828 to "Mesh Proxy Service",
        0x1829 to "Reconnection Configuration",
        0x183A to "Insulin Delivery",
        0x183B to "Binary Sensor",
        0x183C to "Emergency Configuration",
        0x183E to "Physical Activity Monitor",
        0x1843 to "Audio Input Control",
        0x1844 to "Volume Control",
        0x1845 to "Volume Offset Control",
        0x1846 to "Coordinated Set Identification",
        0x1847 to "Device Time",
        0x1848 to "Media Control",
        0x1849 to "Generic Media Control",
        0x184A to "Constant Tone Extension",
        0x184B to "Telephone Bearer",
        0x184C to "Generic Telephone Bearer",
        0x184D to "Microphone Control",
        0x184E to "Audio Stream Control",
        0x184F to "Broadcast Audio Scan",
        0x1850 to "Published Audio Capabilities",
        0x1851 to "Basic Audio Announcement",
        0x1852 to "Broadcast Audio Announcement",
        0x1853 to "Common Audio",
        0x1854 to "Hearing Access",
        0x1855 to "Telephony and Media Audio",
        0x1856 to "Public Broadcast Announcement",
        0x1857 to "Electronic Shelf Label",
        0x1858 to "Gaming Audio",
        0x1859 to "Mesh Proxy Solicitation",
        0x185B to "Ranging Service (RAS)",
        0x1860 to "Tire Pressure Monitoring System Service",
        0xFCB2 to "Location Enabled Advertisement Service",
        0xFD0D to "Blecon Advertising Service",
        0xFD6F to "Exposure Notification Service",
        0xFE0F to "Signify Netherlands B.V. (formerly Philips Lighting) Service",
        0xFE2C to "Fast Pair Service",
        0xFE59 to "Secure DFU Service",
        0xFEAA to "Eddystone",
        0xFEBB to "File Transfer Service by Adafruit",
    )

    /**
     * Member service UUIDs. These are allocated to one company, so seeing one names the
     * maker even when the device advertises no manufacturer data at all.
     */
    val MEMBER_SERVICES: Map<Int, String> = mapOf(
        0xFC27 to "Barking Labs Corp.",
        0xFC28 to "TechnoPartner Tecnologia Ltda.",
        0xFC29 to "Google LLC",
        0xFC2A to "Troo Corporation",
        0xFC2B to "Elder Technologies, Inc",
        0xFC2C to "Verkada Inc.",
        0xFC30 to "Arashi Vision Inc.",
        0xFC31 to "Ford Motor Company",
        0xFC32 to "InPlay, Inc.",
        0xFC34 to "Mitsubishi Electric Corporation",
        0xFC35 to "Metabowerke GmbH",
        0xFC36 to "PharmaSens AG",
        0xFC37 to "TANlock GmbH",
        0xFC38 to "SetPoint Medical",
        0xFC39 to "Harman International",
        0xFC3A to "C.O.B.O. SpA",
        0xFC3B to "BONX INC.",
        0xFC3C to "Eforthink Technology Co., Ltd.",
        0xFC3D to "Reelables, Inc.",
        0xFC3E to "Google LLC",
        0xFC3F to "Milwaukee Electric Tools",
        0xFC41 to "Yoto Limited",
        0xFC43 to "Atmosic Technologies, Inc.",
        0xFC44 to "Block, Inc.",
        0xFC45 to "Mitsubishi Electric Corporation",
        0xFC46 to "Xiaomi",
        0xFC47 to "Shanghai Ingeek Technology Co., Ltd.",
        0xFC48 to "Michelin",
        0xFC49 to "Golioth, Inc.",
        0xFC4A to "Shenzhen Shokz Co.,Ltd.",
        0xFC4B to "WinMagic Inc.",
        0xFC4C to "HP Inc.",
        0xFC4D to "Lodestar Technology Inc.",
        0xFC4E to "Lodestar Technology Inc.",
        0xFC4F to "WaveRF, Corp.",
        0xFC50 to "Ant Group Co., Ltd.",
        0xFC51 to "Ant Group Co., Ltd.",
        0xFC52 to "LG Electronics Inc.",
        0xFC53 to "LEGIC Identsystems AG",
        0xFC54 to "Shenzhen Yinwang Intelligent Technologies Co., Ltd.",
        0xFC55 to "BYD Company Limited",
        0xFC56 to "Google LLC",
        0xFC57 to "Ambient Life Inc.",
        0xFC58 to "Shenzhen Minew Technologies Co., Ltd.",
        0xFC59 to "Ant Group Co., Ltd.",
        0xFC5A to "LAST LOCK INC.",
        0xFC5B to "Time Location Systems AS",
        0xFC5C to "PLASTIC RESEARCH AND DEVELOPMENT CORPORATION",
        0xFC5D to "GP Acoustics International Limited",
        0xFC5E to "KUBU SMART LIMITED",
        0xFC5F to "PI-CRYSTAL INC.",
        0xFC60 to "Ohme Operations UK Limited",
        0xFC61 to "QIKCONNEX LLC",
        0xFC62 to "SPRiNTUS GmbH",
        0xFC63 to "Volvo Technology AB",
        0xFC64 to "Volvo Technology AB",
        0xFC65 to "Robor Electronics B.V.",
        0xFC66 to "Xiaomi Inc.",
        0xFC67 to "Guangdong Hengqin Xingtong Technology Co.,ltd.",
        0xFC68 to "RIGH, INC.",
        0xFC69 to "Harman International",
        0xFC6A to "Sonos Inc",
        0xFC6B to "Sonos Inc",
        0xFC6C to "Powerstick.com",
        0xFC6D to "MOTIVE TECHNOLOGIES, INC.",
        0xFC6E to "stryker",
        0xFC6F to "NextSense, Inc.",
        0xFC70 to "MOTIVE TECHNOLOGIES, INC.",
        0xFC71 to "Hive-Zox International SA",
        0xFC72 to "iodyne, LLC",
        0xFC73 to "Google LLC",
        0xFC74 to "EMBEINT INC",
        0xFC75 to "Xiaomi Inc.",
        0xFC76 to "Weber-Stephen Products LLC",
        0xFC77 to "SING SUN TECHNOLOGY (INTERNATIONAL) LIMITED",
        0xFC78 to "DHL",
        0xFC79 to "LG Electronics Inc.",
        0xFC7A to "Outshiny India Private Limited",
        0xFC7B to "Testo SE & Co. KGaA",
        0xFC7C to "Motorola Mobility, LLC",
        0xFC7D to "MML US, Inc",
        0xFC7E to "Harman International",
        0xFC7F to "Southco",
        0xFC80 to "TELE System Communications Pte. Ltd.",
        0xFC81 to "Axon Enterprise, Inc.",
        0xFC82 to "Zwift, Inc.",
        0xFC83 to "iHealth Labs, Inc.",
        0xFC84 to "NINGBO FOTILE KITCHENWARE CO., LTD.",
        0xFC85 to "Zhejiang Huanfu Technology Co., LTD",
        0xFC86 to "Samsara Networks, Inc",
        0xFC87 to "Samsara Networks, Inc",
        0xFC88 to "CCC del Uruguay",
        0xFC89 to "Intel Corporation",
        0xFC8A to "Intel Corporation",
        0xFC8B to "Kaspersky Lab Middle East FZ-LLC",
        0xFC8C to "VusionGroup",
        0xFC8D to "Caire Inc.",
        0xFC8E to "Blue Iris Labs, Inc.",
        0xFC8F to "Bose Corporation",
        0xFC90 to "Wiliot LTD.",
        0xFC91 to "Samsung Electronics Co., Ltd.",
        0xFC92 to "Furuno Electric Co., Ltd.",
        0xFC93 to "Komatsu Ltd.",
        0xFC94 to "Apple Inc.",
        0xFC95 to "Hippo Camp Software Ltd.",
        0xFC96 to "LEGO System A/S",
        0xFC97 to "Japan Display Inc.",
        0xFC98 to "Ruuvi Innovations Ltd.",
        0xFC99 to "Badger Meter",
        0xFC9A to "Koppli AB",
        0xFC9B to "Merry Electronics (S) Pte Ltd",
        0xFC9D to "Lenovo (Singapore) Pte Ltd.",
        0xFC9E to "Dell Computer Corporation",
        0xFC9F to "Delta Development Team, Inc",
        0xFCA0 to "Apple Inc.",
        0xFCA1 to "PF SCHWEISSTECHNOLOGIE GMBH",
        0xFCA2 to "Meizu Technology Co., Ltd.",
        0xFCA3 to "Gunnebo Aktiebolag",
        0xFCA4 to "HP Inc.",
        0xFCA5 to "HAYWARD INDUSTRIES, INC.",
        0xFCA6 to "Hubble Network Inc.",
        0xFCA7 to "Hubble Network Inc.",
        0xFCA8 to "Medtronic Inc.",
        0xFCA9 to "Medtronic Inc.",
        0xFCAA to "Spintly, Inc.",
        0xFCAB to "IRISS INC.",
        0xFCAC to "IRISS INC.",
        0xFCAD to "Beijing 99help Safety Technology Co., Ltd",
        0xFCAE to "Imagine Marketing Limited",
        0xFCAF to "AltoBeam Inc.",
        0xFCB0 to "Ford Motor Company",
        0xFCB1 to "Google LLC",
        0xFCB2 to "Apple Inc.",
        0xFCB3 to "SWEEN",
        0xFCB4 to "OMRON HEALTHCARE Co., Ltd.",
        0xFCB5 to "OMRON HEALTHCARE Co., Ltd.",
        0xFCB6 to "OMRON HEALTHCARE Co., Ltd.",
        0xFCB7 to "T-Mobile USA",
        0xFCB8 to "Ribbiot, INC.",
        0xFCB9 to "Lumi United Technology Co., Ltd",
        0xFCBA to "BlueID GmbH",
        0xFCBB to "SharkNinja Operating LLC",
        0xFCBC to "Drowsy Digital, Inc.",
        0xFCBD to "Toshiba Corporation",
        0xFCBE to "Musen Connect, Inc.",
        0xFCBF to "ASSA ABLOY Opening Solutions Sweden AB",
        0xFCC0 to "Xiaomi Inc.",
        0xFCC1 to "TIMECODE SYSTEMS LIMITED",
        0xFCC2 to "Qualcomm Technologies, Inc.",
        0xFCC3 to "HP Inc.",
        0xFCC4 to "OMRON(DALIAN) CO,.LTD.",
        0xFCC5 to "OMRON(DALIAN) CO,.LTD.",
        0xFCC6 to "Wiliot LTD.",
        0xFCC7 to "PB INC.",
        0xFCC8 to "Allthenticate, Inc.",
        0xFCC9 to "SkyHawke Technologies",
        0xFCCA to "Cosmed s.r.l.",
        0xFCCB to "TOTO LTD.",
        0xFCCD to "Marshall Group AB",
        0xFCCE to "Luna Health, Inc.",
        0xFCCF to "Google LLC",
        0xFCD0 to "Laerdal Medical AS",
        0xFCD1 to "Shenzhen Benwei Media Co.,Ltd.",
        0xFCD2 to "Allterco Robotics ltd",
        0xFCD3 to "Fisher & Paykel Healthcare",
        0xFCD4 to "OMRON HEALTHCARE",
        0xFCD5 to "Nortek Security & Control",
        0xFCD6 to "SWISSINNO SOLUTIONS AG",
        0xFCD7 to "PowerPal Pty Ltd",
        0xFCD8 to "Appex Factory S.L.",
        0xFCD9 to "Huso, INC",
        0xFCDA to "Draeger",
        0xFCDB to "aconno GmbH",
        0xFCDC to "Amazon.com Services, LLC",
        0xFCDD to "Mobilaris AB",
        0xFCDE to "ARCTOP, INC.",
        0xFCDF to "NIO USA, Inc.",
        0xFCE0 to "Akciju sabiedriba \\\"SAF TEHNIKA\\",
        0xFCE1 to "Sony Group Corporation",
        0xFCE2 to "Baracoda Daily Healthtech",
        0xFCE3 to "Smith & Nephew Medical Limited",
        0xFCE4 to "Samsara Networks, Inc",
        0xFCE5 to "Samsara Networks, Inc",
        0xFCE6 to "Guard RFID Solutions Inc.",
        0xFCE7 to "TKH Security B.V.",
        0xFCE8 to "ITT Industries",
        0xFCE9 to "MindRhythm, Inc.",
        0xFCEA to "Chess Wise B.V.",
        0xFCEB to "Avi-On",
        0xFCEC to "Griffwerk GmbH",
        0xFCED to "Workaround Gmbh",
        0xFCEE to "Velentium, LLC",
        0xFCEF to "Divesoft s.r.o.",
        0xFCF0 to "Security Enhancement Systems, LLC",
        0xFCF1 to "Google LLC",
        0xFCF2 to "Bitwards Oy",
        0xFCF3 to "Armatura LLC",
        0xFCF4 to "Allegion",
        0xFCF5 to "Trident Communication Technology, LLC",
        0xFCF6 to "The Linux Foundation",
        0xFCF7 to "Honor Device Co., Ltd.",
        0xFCF8 to "Honor Device Co., Ltd.",
        0xFCF9 to "Leupold & Stevens, Inc.",
        0xFCFA to "Leupold & Stevens, Inc.",
        0xFCFB to "Shenzhen Benwei Media Co., Ltd.",
        0xFCFC to "Barrot Technology Co.,Ltd.",
        0xFCFD to "Barrot Technology Co.,Ltd.",
        0xFCFE to "Sonova Consumer Hearing GmbH",
        0xFCFF to "701x",
        0xFD00 to "FUTEK Advanced Sensor Technology, Inc.",
        0xFD01 to "Sanvita Medical Corporation",
        0xFD02 to "LEGO System A/S",
        0xFD03 to "Quuppa Oy",
        0xFD04 to "Shure Inc.",
        0xFD05 to "Qualcomm Technologies, Inc.",
        0xFD06 to "RACE-AI LLC",
        0xFD07 to "Swedlock AB",
        0xFD08 to "Bull Group Incorporated Company",
        0xFD09 to "Cousins and Sears LLC",
        0xFD0A to "Luminostics, Inc.",
        0xFD0B to "Luminostics, Inc.",
        0xFD0C to "OSM HK Limited",
        0xFD0D to "Blecon Ltd",
        0xFD0E to "HerdDogg, Inc",
        0xFD0F to "AEON MOTOR CO.,LTD.",
        0xFD10 to "AEON MOTOR CO.,LTD.",
        0xFD11 to "AEON MOTOR CO.,LTD.",
        0xFD12 to "AEON MOTOR CO.,LTD.",
        0xFD13 to "BRG Sports, Inc.",
        0xFD14 to "BRG Sports, Inc.",
        0xFD15 to "Panasonic Corporation",
        0xFD16 to "Sensitech, Inc.",
        0xFD17 to "LEGIC Identsystems AG",
        0xFD18 to "LEGIC Identsystems AG",
        0xFD19 to "Smith & Nephew Medical Limited",
        0xFD1A to "CSIRO",
        0xFD1B to "Helios Sports, Inc.",
        0xFD1C to "Brady Worldwide Inc.",
        0xFD1D to "Samsung Electronics Co., Ltd",
        0xFD1E to "Plume Design Inc.",
        0xFD1F to "3M",
        0xFD20 to "GN Hearing A/S",
        0xFD21 to "Huawei Technologies Co., Ltd.",
        0xFD22 to "Huawei Technologies Co., Ltd.",
        0xFD23 to "DOM Sicherheitstechnik GmbH & Co. KG",
        0xFD24 to "GD Midea Air-Conditioning Equipment Co., Ltd.",
        0xFD25 to "GD Midea Air-Conditioning Equipment Co., Ltd.",
        0xFD26 to "Novo Nordisk A/S",
        0xFD27 to "Integrated Illumination Systems, Inc.",
        0xFD28 to "Julius Blum GmbH",
        0xFD29 to "Asahi Kasei Corporation",
        0xFD2A to "Sony Corporation",
        0xFD2B to "The Access Technologies",
        0xFD2C to "The Access Technologies",
        0xFD2D to "Xiaomi Inc.",
        0xFD2E to "Bitstrata Systems Inc.",
        0xFD2F to "Bitstrata Systems Inc.",
        0xFD30 to "Sesam Solutions BV",
        0xFD31 to "LG Electronics Inc.",
        0xFD32 to "Gemalto Holding BV",
        0xFD33 to "DashLogic, Inc.",
        0xFD34 to "Aerosens LLC.",
        0xFD35 to "Transsion Holdings Limited",
        0xFD36 to "Google LLC",
        0xFD37 to "TireCheck GmbH",
        0xFD38 to "Danfoss A/S",
        0xFD39 to "PREDIKTAS",
        0xFD3A to "Verkada Inc.",
        0xFD3B to "Verkada Inc.",
        0xFD3C to "Redline Communications Inc.",
        0xFD3D to "Woan Technology (Shenzhen) Co., Ltd.",
        0xFD3E to "Pure Watercraft, inc.",
        0xFD3F to "Cognosos, Inc",
        0xFD40 to "Beflex Inc.",
        0xFD41 to "Amazon Lab126",
        0xFD42 to "Globe (Jiangsu) Co.,Ltd",
        0xFD43 to "Apple Inc.",
        0xFD44 to "Apple Inc.",
        0xFD45 to "GB Solution co.,Ltd",
        0xFD46 to "Lemco IKE",
        0xFD47 to "Liberty Global Inc.",
        0xFD48 to "Geberit International AG",
        0xFD49 to "Panasonic Corporation",
        0xFD4A to "Sigma Elektro GmbH",
        0xFD4B to "Samsung Electronics Co., Ltd.",
        0xFD4C to "Adolf Wuerth GmbH & Co KG",
        0xFD4D to "70mai Co.,Ltd.",
        0xFD4E to "70mai Co.,Ltd.",
        0xFD4F to "SONITOR TECHNOLOGIES AS",
        0xFD50 to "Hangzhou Tuya Information  Technology Co., Ltd",
        0xFD51 to "UTC Fire and Security",
        0xFD52 to "UTC Fire and Security",
        0xFD53 to "PCI Private Limited",
        0xFD54 to "Qingdao Haier Technology Co., Ltd.",
        0xFD55 to "Braveheart Wireless, Inc.",
        0xFD56 to "Resmed Ltd",
        0xFD57 to "Volvo Car Corporation",
        0xFD58 to "Volvo Car Corporation",
        0xFD59 to "Samsung Electronics Co., Ltd.",
        0xFD5A to "Samsung Electronics Co., Ltd.",
        0xFD5B to "V2SOFT INC.",
        0xFD5C to "React Mobile",
        0xFD5D to "maxon motor ltd.",
        0xFD5E to "Tapkey GmbH",
        0xFD5F to "Meta Platforms Technologies, LLC",
        0xFD60 to "Sercomm Corporation",
        0xFD61 to "Arendi AG",
        0xFD62 to "Google LLC",
        0xFD63 to "Google LLC",
        0xFD64 to "INRIA",
        0xFD65 to "Razer Inc.",
        0xFD66 to "Zebra Technologies Corporation",
        0xFD67 to "Montblanc Simplo GmbH",
        0xFD68 to "Ubique Innovation AG",
        0xFD69 to "Samsung Electronics Co., Ltd",
        0xFD6A to "Emerson",
        0xFD6B to "rapitag GmbH",
        0xFD6C to "Samsung Electronics Co., Ltd.",
        0xFD6D to "Sigma Elektro GmbH",
        0xFD6E to "Polidea sp. z o.o.",
        0xFD6F to "Apple, Inc.",
        0xFD70 to "GuangDong Oppo Mobile Telecommunications Corp., Ltd",
        0xFD71 to "GN Hearing A/S",
        0xFD72 to "Logitech International SA",
        0xFD73 to "BRControls Products BV",
        0xFD74 to "BRControls Products BV",
        0xFD75 to "Insulet Corporation",
        0xFD76 to "Insulet Corporation",
        0xFD77 to "Withings",
        0xFD78 to "Withings",
        0xFD79 to "Withings",
        0xFD7A to "Withings",
        0xFD7B to "WYZE LABS, INC.",
        0xFD7C to "Toshiba Information Systems(Japan) Corporation",
        0xFD7D to "Center for Advanced Research Wernher Von Braun",
        0xFD7E to "Samsung Electronics Co., Ltd.",
        0xFD7F to "Husqvarna AB",
        0xFD80 to "Phindex Technologies, Inc",
        0xFD81 to "CANDY HOUSE, Inc.",
        0xFD82 to "Sony Corporation",
        0xFD83 to "iNFORM Technology GmbH",
        0xFD84 to "Tile, Inc.",
        0xFD85 to "Husqvarna AB",
        0xFD86 to "Abbott",
        0xFD87 to "Google LLC",
        0xFD88 to "Urbanminded LTD",
        0xFD89 to "Urbanminded LTD",
        0xFD8A to "Signify Netherlands B.V.",
        0xFD8B to "Jigowatts Inc.",
        0xFD8C to "Google LLC",
        0xFD8D to "quip NYC Inc.",
        0xFD8E to "Motorola Solutions",
        0xFD90 to "Guangzhou SuperSound Information Technology Co.,Ltd",
        0xFD91 to "Groove X, Inc.",
        0xFD92 to "Qualcomm Technologies International, Ltd. (QTIL)",
        0xFD93 to "Bayerische Motoren Werke AG",
        0xFD94 to "Hewlett Packard Enterprise",
        0xFD95 to "Rigado",
        0xFD96 to "Google LLC",
        0xFD97 to "June Life, Inc.",
        0xFD98 to "Disney Worldwide Services, Inc.",
        0xFD99 to "ABB Oy",
        0xFD9A to "Huawei Technologies Co., Ltd.",
        0xFD9B to "Huawei Technologies Co., Ltd.",
        0xFD9C to "Huawei Technologies Co., Ltd.",
        0xFD9D to "Gastec Corporation",
        0xFD9E to "The Coca-Cola Company",
        0xFD9F to "VitalTech Affiliates LLC",
        0xFDA0 to "Secugen Corporation",
        0xFDA1 to "Groove X, Inc",
        0xFDA2 to "Groove X, Inc",
        0xFDA3 to "Inseego Corp.",
        0xFDA4 to "Inseego Corp.",
        0xFDA5 to "Neurostim OAB, Inc.",
        0xFDA6 to "WWZN Information Technology Company Limited",
        0xFDA7 to "WWZN Information Technology Company Limited",
        0xFDA8 to "PSA Peugeot Citroën",
        0xFDA9 to "Rhombus Systems, Inc.",
        0xFDAA to "Xiaomi Inc.",
        0xFDAB to "Xiaomi Inc.",
        0xFDAC to "Tentacle Sync GmbH",
        0xFDAD to "Houwa System Design, k.k.",
        0xFDAE to "Houwa System Design, k.k.",
        0xFDAF to "Wiliot LTD",
        0xFDB0 to "Oura Health Ltd",
        0xFDB1 to "Oura Health Ltd",
        0xFDB2 to "Portable Multimedia Ltd",
        0xFDB3 to "Audiodo AB",
        0xFDB4 to "HP Inc",
        0xFDB5 to "ECSG",
        0xFDB6 to "GWA Hygiene GmbH",
        0xFDB7 to "LivaNova USA Inc.",
        0xFDB8 to "LivaNova USA Inc.",
        0xFDBB to "Profoto",
        0xFDBC to "Emerson",
        0xFDBD to "Clover Network, Inc.",
        0xFDBE to "California Things Inc.",
        0xFDBF to "California Things Inc.",
        0xFDC0 to "Hunter Douglas",
        0xFDC1 to "Hunter Douglas",
        0xFDC2 to "Baidu Online Network Technology (Beijing) Co., Ltd",
        0xFDC3 to "Baidu Online Network Technology (Beijing) Co., Ltd",
        0xFDC4 to "Simavita (Aust) Pty Ltd",
        0xFDC5 to "Automatic Labs",
        0xFDC6 to "Eli Lilly and Company",
        0xFDC7 to "Eli Lilly and Company",
        0xFDC8 to "Hach – Danaher",
        0xFDC9 to "Busch-Jaeger Elektro GmbH",
        0xFDCA to "Fortin Electronic Systems",
        0xFDCB to "Meggitt SA",
        0xFDCC to "Shoof Technologies",
        0xFDCD to "Qingping Technology (Beijing) Co., Ltd.",
        0xFDCE to "SENNHEISER electronic GmbH & Co. KG",
        0xFDCF to "Nalu Medical, Inc",
        0xFDD0 to "Huawei Technologies Co., Ltd",
        0xFDD1 to "Huawei Technologies Co., Ltd",
        0xFDD2 to "Bose Corporation",
        0xFDD3 to "FUBA Automotive Electronics GmbH",
        0xFDD4 to "LX Solutions Pty Limited",
        0xFDD5 to "Brompton Bicycle Ltd",
        0xFDD6 to "Ministry of Supply",
        0xFDD7 to "Copeland Cold Chain LP",
        0xFDD8 to "Jiangsu Teranovo Tech Co., Ltd.",
        0xFDD9 to "Jiangsu Teranovo Tech Co., Ltd.",
        0xFDDA to "MHCS",
        0xFDDB to "Samsung Electronics Co., Ltd.",
        0xFDDC to "4iiii Innovations Inc.",
        0xFDDD to "Arch Systems Inc",
        0xFDDE to "Noodle Technology Inc.",
        0xFDDF to "Harman International",
        0xFDE0 to "John Deere",
        0xFDE1 to "Fortin Electronic Systems",
        0xFDE2 to "Google LLC",
        0xFDE3 to "Abbott Diabetes Care",
        0xFDE4 to "JUUL Labs, Inc.",
        0xFDE5 to "SMK Corporation",
        0xFDE6 to "Intelletto Technologies Inc",
        0xFDE7 to "SECOM Co., LTD",
        0xFDE8 to "Robert Bosch GmbH",
        0xFDE9 to "Spacesaver Corporation",
        0xFDEA to "SeeScan, Inc",
        0xFDEB to "Syntronix Corporation",
        0xFDEC to "Mannkind Corporation",
        0xFDED to "Pole Star",
        0xFDEE to "Huawei Technologies Co., Ltd.",
        0xFDEF to "ART AND PROGRAM, INC.",
        0xFDF0 to "Google LLC",
        0xFDF1 to "LAMPLIGHT Co.,Ltd",
        0xFDF2 to "AMICCOM Electronics Corporation",
        0xFDF3 to "Amersports",
        0xFDF4 to "O. E. M. Controls, Inc.",
        0xFDF5 to "Milwaukee Electric Tools",
        0xFDF6 to "AIAIAI ApS",
        0xFDF7 to "HP Inc.",
        0xFDF8 to "Onvocal",
        0xFDF9 to "INIA",
        0xFDFA to "Tandem Diabetes Care",
        0xFDFB to "Tandem Diabetes Care",
        0xFDFC to "Optrel AG",
        0xFDFD to "RecursiveSoft Inc.",
        0xFDFE to "ADHERIUM(NZ) LIMITED",
        0xFDFF to "OSRAM GmbH",
        0xFE00 to "Amazon.com Services, Inc.",
        0xFE01 to "Duracell U.S. Operations Inc.",
        0xFE02 to "Robert Bosch GmbH",
        0xFE03 to "Amazon.com Services, Inc.",
        0xFE04 to "Motorola Solutions, Inc.",
        0xFE05 to "CORE Transport Technologies NZ Limited",
        0xFE06 to "Qualcomm Technologies, Inc.",
        0xFE07 to "Sonos, Inc.",
        0xFE08 to "Microsoft",
        0xFE09 to "Pillsy, Inc.",
        0xFE0A to "ruwido austria gmbh",
        0xFE0B to "ruwido austria gmbh",
        0xFE0C to "Procter & Gamble",
        0xFE0D to "Procter & Gamble",
        0xFE0E to "Setec Pty Ltd",
        0xFE0F to "Signify Netherlands B.V. (formerly Philips Lighting B.V.)",
        0xFE10 to "LAPIS Technology Co., Ltd.",
        0xFE11 to "GMC-I Messtechnik GmbH",
        0xFE12 to "M-Way Solutions GmbH",
        0xFE13 to "Apple Inc.",
        0xFE14 to "Flextronics International USA Inc.",
        0xFE15 to "Amazon.com Services, Inc..",
        0xFE16 to "Footmarks, Inc.",
        0xFE17 to "Telit Wireless Solutions GmbH",
        0xFE18 to "Runtime, Inc.",
        0xFE19 to "Google LLC",
        0xFE1A to "Tyto Life LLC",
        0xFE1B to "Tyto Life LLC",
        0xFE1C to "NetMedia, Inc.",
        0xFE1D to "Illuminati Instrument Corporation",
        0xFE1E to "LAMPLIGHT Co., Ltd.",
        0xFE1F to "Garmin International, Inc.",
        0xFE20 to "Emerson",
        0xFE21 to "Bose Corporation",
        0xFE22 to "Zoll Medical Corporation",
        0xFE23 to "Zoll Medical Corporation",
        0xFE24 to "August Home Inc",
        0xFE25 to "Apple, Inc.",
        0xFE26 to "Google LLC",
        0xFE27 to "Google LLC",
        0xFE28 to "Ayla Networks",
        0xFE29 to "Gibson Innovations",
        0xFE2A to "DaisyWorks, Inc.",
        0xFE2B to "ITT Industries",
        0xFE2C to "Google LLC",
        0xFE2D to "LAMPLIGHT Co., Ltd.",
        0xFE2E to "ERi,Inc.",
        0xFE2F to "CRESCO Wireless, Inc",
        0xFE30 to "Volkswagen AG",
        0xFE31 to "Volkswagen AG",
        0xFE32 to "Pro-Mark, Inc.",
        0xFE33 to "CHIPOLO d.o.o.",
        0xFE34 to "SmallLoop LLC",
        0xFE35 to "HUAWEI Technologies Co., Ltd",
        0xFE36 to "HUAWEI Technologies Co., Ltd",
        0xFE39 to "TTS Tooltechnic Systems AG & Co. KG",
        0xFE3A to "TTS Tooltechnic Systems AG & Co. KG",
        0xFE3B to "Dolby Laboratories",
        0xFE3C to "alibaba",
        0xFE3D to "BD Medical",
        0xFE3E to "BD Medical",
        0xFE3F to "Friday Labs Limited",
        0xFE40 to "Inugo Systems Limited",
        0xFE41 to "Inugo Systems Limited",
        0xFE42 to "Nets A/S",
        0xFE43 to "Andreas Stihl AG & Co. KG",
        0xFE44 to "SK Telecom",
        0xFE45 to "Snapchat Inc",
        0xFE46 to "B&O Play A/S",
        0xFE47 to "General Motors",
        0xFE48 to "General Motors",
        0xFE49 to "SenionLab AB",
        0xFE4A to "OMRON HEALTHCARE Co., Ltd.",
        0xFE4B to "Signify Netherlands B.V. (formerly Philips Lighting B.V.)",
        0xFE4C to "Volkswagen AG",
        0xFE4D to "Casambi Technologies Oy",
        0xFE4E to "NTT docomo",
        0xFE4F to "Molekule, Inc.",
        0xFE50 to "Google LLC",
        0xFE51 to "SRAM",
        0xFE52 to "SetPoint Medical",
        0xFE53 to "3M",
        0xFE54 to "Motiv, Inc.",
        0xFE55 to "Google LLC",
        0xFE56 to "Google LLC",
        0xFE57 to "Dotted Labs",
        0xFE58 to "Nordic Semiconductor ASA",
        0xFE59 to "Nordic Semiconductor ASA",
        0xFE5A to "Cronologics Corporation",
        0xFE5B to "GT-tronics HK Ltd",
        0xFE5C to "million hunters GmbH",
        0xFE5D to "Grundfos A/S",
        0xFE5E to "Plastc Corporation",
        0xFE5F to "Eyefi, Inc.",
        0xFE60 to "Lierda Science & Technology Group Co., Ltd.",
        0xFE61 to "Logitech International SA",
        0xFE62 to "Indagem Tech LLC",
        0xFE63 to "Connected Yard, Inc.",
        0xFE64 to "Siemens AG",
        0xFE65 to "CHIPOLO d.o.o.",
        0xFE66 to "Intel Corporation",
        0xFE67 to "Lab Sensor Solutions",
        0xFE68 to "Capsle Technologies Inc.",
        0xFE69 to "Capsle Technologies Inc.",
        0xFE6A to "Kontakt Micro-Location Sp. z o.o.",
        0xFE6B to "TASER International, Inc.",
        0xFE6C to "TASER International, Inc.",
        0xFE6D to "The University of Tokyo",
        0xFE6E to "The University of Tokyo",
        0xFE6F to "LINE Corporation",
        0xFE70 to "Beijing Jingdong Century Trading Co., Ltd.",
        0xFE71 to "Plume Design Inc",
        0xFE72 to "Abbott Medical (formerly St. Jude Medical, Inc.)",
        0xFE73 to "Abbott Medical (formerly St. Jude Medical, Inc.)",
        0xFE74 to "unwire",
        0xFE75 to "TangoMe",
        0xFE76 to "TangoMe",
        0xFE77 to "Hewlett-Packard Company",
        0xFE78 to "Hewlett-Packard Company",
        0xFE79 to "Zebra Technologies",
        0xFE7A to "Bragi GmbH",
        0xFE7B to "Orion Labs, Inc.",
        0xFE7C to "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)",
        0xFE7D to "Aterica Health Inc.",
        0xFE7E to "Awear Solutions Ltd",
        0xFE7F to "Doppler Lab",
        0xFE80 to "Doppler Lab",
        0xFE81 to "Medtronic Inc.",
        0xFE82 to "Medtronic Inc.",
        0xFE83 to "Blue Bite",
        0xFE84 to "RF Digital Corp",
        0xFE85 to "RF Digital Corp",
        0xFE86 to "HUAWEI Technologies Co., Ltd",
        0xFE87 to "Qingdao Yeelink Information Technology Co., Ltd. ( 青岛亿联客信息技术有限公司 )",
        0xFE88 to "SALTO SYSTEMS S.L.",
        0xFE89 to "B&O Play A/S",
        0xFE8A to "Apple, Inc.",
        0xFE8B to "Apple, Inc.",
        0xFE8C to "TRON Forum",
        0xFE8D to "Interaxon Inc.",
        0xFE8E to "ARM Ltd",
        0xFE8F to "CSR",
        0xFE90 to "JUMA",
        0xFE91 to "Shanghai Imilab Technology Co.,Ltd",
        0xFE92 to "Jarden Safety & Security",
        0xFE93 to "OttoQ In",
        0xFE94 to "OttoQ In",
        0xFE95 to "Xiaomi Inc.",
        0xFE96 to "Tesla Motors Inc.",
        0xFE97 to "Tesla Motors Inc.",
        0xFE98 to "Currant Inc",
        0xFE99 to "Currant Inc",
        0xFE9A to "Estimote",
        0xFE9B to "Samsara Networks, Inc",
        0xFE9C to "GSI Laboratories, Inc.",
        0xFE9D to "Mobiquity Networks Inc",
        0xFE9E to "Renesas Design Netherlands B.V.",
        0xFE9F to "Google LLC",
        0xFEA0 to "Google LLC",
        0xFEA3 to "ITT Industries",
        0xFEA4 to "Paxton Access Ltd",
        0xFEA5 to "GoPro, Inc.",
        0xFEA6 to "GoPro, Inc.",
        0xFEA7 to "UTC Fire and Security",
        0xFEA8 to "Savant Systems LLC",
        0xFEA9 to "Savant Systems LLC",
        0xFEAA to "Google LLC",
        0xFEAB to "Nokia",
        0xFEAC to "Nokia",
        0xFEAD to "Nokia",
        0xFEAE to "Nokia",
        0xFEAF to "Nest Labs Inc",
        0xFEB0 to "Nest Labs Inc",
        0xFEB1 to "Electronics Tomorrow Limited",
        0xFEB2 to "Microsoft Corporation",
        0xFEB3 to "Taobao",
        0xFEB4 to "WiSilica Inc.",
        0xFEB5 to "WiSilica Inc.",
        0xFEB6 to "Vencer Co., Ltd",
        0xFEB7 to "Meta Platforms, Inc.",
        0xFEB8 to "Meta Platforms, Inc.",
        0xFEB9 to "LG Electronics",
        0xFEBA to "Tencent Holdings Limited",
        0xFEBB to "adafruit industries",
        0xFEBC to "Dexcom Inc",
        0xFEBD to "Clover Network, Inc",
        0xFEBE to "Bose Corporation",
        0xFEBF to "Nod, Inc.",
        0xFEC0 to "KDDI Corporation",
        0xFEC1 to "KDDI Corporation",
        0xFEC2 to "Blue Spark Technologies, Inc.",
        0xFEC3 to "360fly, Inc.",
        0xFEC4 to "PLUS Location Systems",
        0xFEC5 to "Realtek Semiconductor Corp.",
        0xFEC6 to "Kocomojo, LLC",
        0xFEC7 to "Apple, Inc.",
        0xFEC8 to "Apple, Inc.",
        0xFEC9 to "Apple, Inc.",
        0xFECA to "Apple, Inc.",
        0xFECB to "Apple, Inc.",
        0xFECC to "Apple, Inc.",
        0xFECD to "Apple, Inc.",
        0xFECE to "Apple, Inc.",
        0xFECF to "Apple, Inc.",
        0xFED0 to "Apple, Inc.",
        0xFED1 to "Apple, Inc.",
        0xFED2 to "Apple, Inc.",
        0xFED3 to "Apple, Inc.",
        0xFED4 to "Apple, Inc.",
        0xFED5 to "Plantronics Inc.",
        0xFED6 to "Broadcom",
        0xFED7 to "Broadcom",
        0xFED8 to "Google LLC",
        0xFED9 to "Pebble Technology Corporation",
        0xFEDA to "ISSC Technologies Corp.",
        0xFEDB to "Perka, Inc.",
        0xFEDC to "Jawbone",
        0xFEDD to "Jawbone",
        0xFEDE to "Coin, Inc.",
        0xFEE0 to "Anhui Huami Information Technology Co., Ltd.",
        0xFEE1 to "Anhui Huami Information Technology Co., Ltd.",
        0xFEE2 to "Anki, Inc.",
        0xFEE3 to "Anki, Inc.",
        0xFEE4 to "Nordic Semiconductor ASA",
        0xFEE5 to "Nordic Semiconductor ASA",
        0xFEE6 to "Silvair, Inc.",
        0xFEE7 to "Tencent Holdings Limited.",
        0xFEE8 to "Quintic Corp.",
        0xFEE9 to "Quintic Corp.",
        0xFEEA to "Swirl Networks, Inc.",
        0xFEEB to "Swirl Networks, Inc.",
        0xFEEC to "Tile, Inc.",
        0xFEED to "Tile, Inc.",
        0xFEEE to "Polar Electro Oy",
        0xFEEF to "Polar Electro Oy",
        0xFEF0 to "Intel",
        0xFEF1 to "CSR",
        0xFEF2 to "CSR",
        0xFEF3 to "Google LLC",
        0xFEF4 to "Google LLC",
        0xFEF5 to "Dialog Semiconductor GmbH",
        0xFEF6 to "Wicentric, Inc.",
        0xFEF7 to "Aplix Corporation",
        0xFEF8 to "Aplix Corporation",
        0xFEF9 to "PayPal, Inc.",
        0xFEFA to "PayPal, Inc.",
        0xFEFB to "Telit Wireless Solutions (Formerly Stollmann E+V GmbH)",
        0xFEFC to "Gimbal, Inc.",
        0xFEFD to "Gimbal, Inc.",
        0xFEFE to "GN Hearing A/S",
        0xFEFF to "GN Netcom",
    )
}
